### ISSUE TITLE
AirshipConfigOptions unclear

### ISSUE THREAD

**Issue by alexthekid07** [urbanairship/urbanairship-xamarin#177]
Trying to follow the Xamarin SDK instructions (I'm using the NETStandard package), and I'm using my own custom Autopilot class for Xamarin.Android but there are a few things not well documented (IMO) with AirshipConfigOptions:

- I don't see any obvious documentation on how to actually utilize airshipconfig.properties, It seems that by default, this file is not consumed, and the Xamarin guide only instructs you on how to make your own custom Autopilot class. How do I ignore my custom Autopilot class and just use the contents properties file?
- SetLogLevel() expects an int. What do I feed this? I don't see any obvious list of enums.
- SetNotificationAccentColor() expects an int. What do I feed this for a color, as an int???
- .SetNotificationIcon() expects an int. What do I feed this?

In addition there are a couple other things not made entirely clear for Xamarin:
- The documentation implies TakeOff happens automatically. I don't want to TakeOff for push notifications until a user gets past my login screen. How do I defer this and manually TakeOff later?
- If a user "logs out" of what would be their NamedUser, how do I de-register them from the standpoint of Xamarin.Forms/Xamarin.Android/Xamarin.iOS so they stop receiving pushes for this NamedUser?

**Comment by marc-scig** [comment]
Hi @alexthekid07,

Some of these details are covered in the [Getting started guide](https://docs.airship.com/platform/xamarin/getting-started/). For instance, if you're not using Autopilot the  config options are consumed in the platform specific sections of your app: Assets/airshipconfig.properties for android, (with a AndroidAsset build action) and AirshipConfig.plist added with a BundleResource build action in iOS.

For the enums, it might helpful to check out the [Android SDK API docs](https://docs.airship.com/reference/libraries/android/latest/reference/packages.html). Our android bindings are automatically generated and it's a large codebase, which makes generating API docs for the bindings problematic. But you can usually figure things out from there, with minor adjustments for C# conventions like camel casing, properties instead of basic setters/getters, etc.

Regarding takeOff, if you don't want it to happen automatically then Autopilot will probably not work for you. The alternative is to call takeOff on your own in the native section of your app.

Named users are disassociated by setting the identifier to null/nil or an empty string.

I hope this helps. If you have additional difficulty, I'd suggest contacting support.
